{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kivo.nidalib",
    "module": "final",
    "version": "1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "iz6ybvyxx5fehduz72xghmnzqi"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "final-1.5.aar",
          "url": "final-1.5.aar",
          "size": 22050685,
          "sha512": "13e45a27469f81c712b212bb27e68478c9cf0d52aaf9e8ccc5f4b4553fb70a0a9adf9fed7604d6a6e1b00686ef5bdadc1e6db832a1dfec15beb785a2b60477a2",
          "sha256": "f7f6f7e579cdaef9471365d1497a1a18f1b649530d350fc411a1098dca03162d",
          "sha1": "c9a1eddd0d87e78c2c68197be154ccd807616302",
          "md5": "9d8d842f03e78bccaa90394d86ecf963"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.0.0-alpha28"
          }
        }
      ],
      "files": [
        {
          "name": "final-1.5.aar",
          "url": "final-1.5.aar",
          "size": 22050685,
          "sha512": "13e45a27469f81c712b212bb27e68478c9cf0d52aaf9e8ccc5f4b4553fb70a0a9adf9fed7604d6a6e1b00686ef5bdadc1e6db832a1dfec15beb785a2b60477a2",
          "sha256": "f7f6f7e579cdaef9471365d1497a1a18f1b649530d350fc411a1098dca03162d",
          "sha1": "c9a1eddd0d87e78c2c68197be154ccd807616302",
          "md5": "9d8d842f03e78bccaa90394d86ecf963"
        }
      ]
    }
  ]
}
